### ISSUE TITLE
Create speaker on the ceiling #38

### ISSUE THREAD

**Issue by HHS81** [HHS81/c182-Textures#1]
Created speaker and added a first texture (for debugging propose)

**Comment by gilbertohasnofb** [comment]
I can't find where this texture is! Can you orientate me, please? I have a very nice speaker texture which I'm ready to apply :smile:

**Comment by HHS81** [comment]
![speaker_position](https://cloud.githubusercontent.com/assets/12649375/12688780/bded2634-c6d8-11e5-9413-f87e1f0447bc.jpg)

**Comment by HHS81** [comment]
And yes, the underlying uvmap fits - I tested it! :smile:

**Comment by gilbertohasnofb** [comment]
Ok! Thanks!

**Comment by gilbertohasnofb** [comment]
Done:

![fg-0](https://cloud.githubusercontent.com/assets/5700795/12690117/8ef927b6-c6e1-11e5-86d8-bd378587640c.jpg)

![fg-1](https://cloud.githubusercontent.com/assets/5700795/12690116/8e9caf54-c6e1-11e5-815f-e4cf122498ac.jpg)

**Comment by HHS81** [comment]
Looks great!

**Comment by gilbertohasnofb** [comment]
Thanks, Heiko! :smiley:
