### ISSUE TITLE
Questoin regarding state of this repo

### ISSUE THREAD

**Issue by hbeni** [HHS81/c182-Textures#12]
Hi @HHS81,
What is the reason for separating the development textures file into a separate repo?
Because, aircraft devs may very probably have both repos tracked locally anyways, and Texture changes affect the results in the aircraft repo; I would propose that:
* I consolidate the outstanding texture merge requests into a consistent state
* Then I upload the sources to the `dev` tree in the c182s repo (which is excluded when releasing to FGAddon)

Alternatively, I ask for write permission in this repo here, so I can clean up some old bits.
But I'd rather have one single development point...

**Comment by HHS81** [comment]
It is already almost 10 years ago since we decided to have an extra texture-repo. But so far as I can remember the developement of the textures wasn`t trivial, and the source files not small. So it was easier to split them up. I can give you permission of course, I thought you already had.

**Comment by HHS81** [comment]
you should already have write permission....

**Comment by hbeni** [comment]
Ah okay!
Last time i checked, I had no merge capability.

Will clean up here and bring it up-to-date.
Thanks.

**Comment by HHS81** [comment]
please check, Github had some changes, but I don`t see why you don't should have merge capability.

**Comment by hbeni** [comment]
Checked positively. At least the button is there.

**Comment by hbeni** [comment]
Finished. All seems up to date now.
